[OpenAI]
API_TYPE = openai
# 換成你的 API Key
API_KEY = sk-your-api-key-here 
# 換成你的 Model
MODEL = gpt-5-mini
TIMEOUT = 120

[Simulation]
RAISE_EXCEPTIONS = True

[Cognition]
ENABLE_MEMORY_CONSOLIDATION = False